/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace.$workspaceId'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiAcceptInviteRouteImport } from './routes/api/accept-invite'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcceptInviteRoute = ApiAcceptInviteRouteImport.update({
  id: '/api/accept-invite',
  path: '/api/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coming-soon': typeof ComingSoonRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/api/accept-invite': typeof ApiAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coming-soon': typeof ComingSoonRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/api/accept-invite': typeof ApiAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coming-soon': typeof ComingSoonRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/api/accept-invite': typeof ApiAcceptInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/coming-soon'
    | '/home'
    | '/login'
    | '/my-tasks'
    | '/pending'
    | '/signup'
    | '/admin/approvals'
    | '/api/accept-invite'
    | '/auth/callback'
    | '/board/$boardId'
    | '/workspace/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/coming-soon'
    | '/home'
    | '/login'
    | '/my-tasks'
    | '/pending'
    | '/signup'
    | '/admin/approvals'
    | '/api/accept-invite'
    | '/auth/callback'
    | '/board/$boardId'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/coming-soon'
    | '/home'
    | '/login'
    | '/my-tasks'
    | '/pending'
    | '/signup'
    | '/admin/approvals'
    | '/api/accept-invite'
    | '/auth/callback'
    | '/board/$boardId'
    | '/workspace/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ComingSoonRoute: typeof ComingSoonRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MyTasksRoute: typeof MyTasksRoute
  PendingRoute: typeof PendingRoute
  SignupRoute: typeof SignupRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  ApiAcceptInviteRoute: typeof ApiAcceptInviteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accept-invite': {
      id: '/api/accept-invite'
      path: '/api/accept-invite'
      fullPath: '/api/accept-invite'
      preLoaderRoute: typeof ApiAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ComingSoonRoute: ComingSoonRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MyTasksRoute: MyTasksRoute,
  PendingRoute: PendingRoute,
  SignupRoute: SignupRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  ApiAcceptInviteRoute: ApiAcceptInviteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
